### ISSUE TITLE
External link arrow overflowing on mobile

### ISSUE THREAD

**Issue by schlosser** [jhil/jeffanders-2022#14]
![Screenshot_20220221-114053](https://user-images.githubusercontent.com/2433509/155004733-10c515b9-6f7a-4430-96bb-bc78c06fe115.png)

The external link arrow seems a bit out of place here

**Comment by jhil** [comment]
lol thanks for finding this, Dan!

**Comment by jhil** [comment]
I haven't done any responsiveness on posts yet. I should!
