### ISSUE TITLE
Sidenav should highlight the section you're viewing

### ISSUE THREAD

**Issue by yefim** [jhil/jeffanders-2022#36]
For example:

<img width="289" alt="Screen Shot 2022-03-04 at 1 00 57 PM" src="https://user-images.githubusercontent.com/1170843/156817126-8c43c10c-c854-43f5-970f-16a01118b886.png">

**Comment by jhil** [comment]
Good eye! This got messed up in my very last push, so I need to investigate.

https://github.com/jhil/jeffanders-2022/issues/33
