### ISSUE TITLE
Lots of problems past large 4 column breakpoint 

### ISSUE THREAD

**Issue by jhil** [jhil/jeffanders-2022#40]
Did too much testing below 1280 😄

**Comment by jhil** [comment]
h/t @brianlovin and @schlosser

**Comment by brianlovin** [comment]
Get this lad a 16" MacBook!

**Comment by jhil** [comment]
- [ ] Wrapping text within compact cards -> larger dimension for 4-column breakpoint
- [ ] Only 6 teams showing up in 4 column layout, other sections too -> increase post limits per category to multiple of 4
- [ ] Horizontal overflow
